
spring:
     application:
          name: spirng-boot-rabbitmq
     rabbitmq:
          host: 192.168.13.64
          port: 5672
          username: hbsit
          password: hbsit
          virtual-host: /hbsit
          #exchange: EXCHANGE_DIRECT_ORDER_MARKET 
          #queue: QUEUE_ISSUED_NAME_LIST
          #bean: rabbitTemplate      